#!/bin/bash

# Color
red='\e[31m'
green='\e[32m'
blue='\e[34m'
white='\e[97m'
codename='Sniper'
ver='1.2'
follow='pikpikcu'
site=$1


all(){
    logo
    echo -e "\n${red}Start ${green}[Subdomain Enumerate...]${white}"
    assetfinder --subs-only $site > $output/$site.txt
    cat $output/$site.txt | sort -u > $output/subs.txt
    rm -rf $output/$site.txt
    echo -e "FOUND SUBDOMAINS [${green}$(cat $output/subs.txt | wc -l)${white}]"
    echo -e "${red}Success Saved:${green}[$output/subs.txt]"
    echo -e "${red}Start ${green}[Check Host Live...]${white}"
    cat $output/subs.txt | sort -u | httprobe | tee -a  > $output/$site-host.txt
    echo -e "Resluts Live:[${green}$(cat $output/$site-host.txt | wc -l)${white}]"
    echo -e "${red}Success Saved:${green}[$output/$site-host.txt]"
    echo -e "${red}Start ${green}[Check Status Response...]${white}"
    cat $output/subs.txt | hakrawler -plain | hakcheckurl | grep -v 404 > $output/$site-dir.txt 
    echo -e "Found Status Dir [${green}$(cat $output/$site-dir.txt | wc -l)${white}]"
    echo -e "${red}Success Saved:${green}[$output/$site-dir.txt]"
    echo -e "${red}Start ${green}[Scraping wayback for data...]${white}"
    cat $output/subs.txt | waybackurls | sort -u > $output/$site-list.txt
    echo -e "Found Scraping [${green}$(cat $output/$site-list.txt | wc -l)${white}]"
    echo -e "${red}Success Saved:${green}[$output/$site-list.txt]"
    echo -e "${red}Start ${green}[Scraping wayback for data js...]${white}"
   # cat $output/subs.txt | waybackurls | sort -u > $output/scraping/$site-list.txt
    cat $output/$site-list.txt | sort -u | grep -P "\w+\.js(\?|$)" | sort -u > $output/jsurls.txt
    echo -e "Found Scraping [${green}$(cat $output/jsurls.txt | wc -l)${white}]"
    echo -e "${red}Success Saved:${green}[$output/jsurls.txt]"
    echo -e "${red}Start ${green}[Scraping wayback for data php...]${white}" 
    cat $output/$site-list.txt | sort -u | grep -P "\w+\.php(\?|$)" | sort -u > $output/phpurls.txt
    echo -e "Found Scraping [${green}$(cat $output/phpurls.txt | wc -l)${white}]"
    echo -e "${red}Success Saved:${green}[$output/phpurls.txt]"
    echo -e "${red}Start ${green}[Scraping wayback for data aspx...]${white}"
    cat $output/$site-list.txt | sort -u | grep -P "\w+\.aspx(\?|$)" | sort -u > $output/spurls.txt
    echo -e "Found Scraping [${green}$(cat $output/aspurls.txt | wc -l)${white}]"
    echo -e "${red}Success Saved:${green}[$output/aspurls.txt]"
    echo -e "${red}Start ${green}[Check Open Redirection...]${white}"
    cat $output/subs.txt | grep -e 'redirect\|redirect=\|url\|url=\|next=\|dest=\|destination\|return\|go\|redirect_uri\|continue=\|return_path=\|externalLink=\|URL' > $output/$site-redirect.txt          
    echo -e "Found Check URL Redirection [${green}$(ls $output/$site-redirect.txt  | wc -l)${white}]"
    echo -e "${red}Success Saved:${green}[$output/$site-redirect.txt ]"
    echo -e "${red}Start ${green}[ Blind SSRF testing...]${white}"
    ssr=`cat callback.txt`
    cat $output/subs.txt | waybackurls > $output/$site-ssrf.txt
    cat $output/subs.txt | gau >> $output/$site-ssrf.txt
    cat $output/$site-ssrf.txt | sort | uniq | grep "?" | qsreplace -a | qsreplace $ssr > $output/$site-ssrf2.txt
    sed -i "s|$|\&dest=$ssr\&redirect=$ssr\&uri=$ssr\&path=$ssr\&continue=$ssr\&url=$ssr\&window=$ssr\&next=$ssr\&data=$ssr\&reference=$ssr\&ssr=$ssr\&html=$ssr\&val=$ssr\&validate=$ssr\&domain=$ssr\&callback=$ssr\&return=$ssr\&page=$ssr\&feed=$ssr\&host=$ssr&\port=$ssr\&to=$ssr\&out=$ssr\&view=$ssr\&dir=$ssr\&show=$ssr\&navigation=$ssr\&open=$ssr|g" $output/ssrf/$site-ssrf2.txt
    ffuf -w $output/$site-ssrf2.txt -u FUZZ -t 50  > $output/ssrf/$site-ssrf3.txt
    #echo -e "Found Check SSRF [${green}$(cat $output/ssrf/$site-ssrf3.txt | wc -l)${white}]"
    echo -e "\n${red}Success Saved:${green}[$output/$site-ssrf3.txt]"
    echo
    
}

subdo(){
    logo
    echo -e "\n${red}Start ${green}[Subdomain Enumerate...]${white}"
    while [ "$site" ];do
        if [ ! -f ~/go/bin/assetfinder ];
            then
            echo -e "${red}[+]${green} Assetfinder Not Install!\n"
            exit 1
        elif [ ! -f ~/go/bin/subfinder ];
            then
            echo -e "${red}[+]${green} Subfinder Not Install!\n"
            exit 1            

        else
            assetfinder --subs-only $site > $output/subdo/$site.txt
            subfinder -silent -d $site >> $output/subdo/$site.txt
            cat $output/subdo/$site.txt | sort -u > $output/subdo/subs.txt
            rm -rf $output/subdo/$site.txt
        fi
    echo -e "FOUND SUBDOMAINS [${green}$(cat $output/subdo/subs.txt | wc -l)${white}]"
    echo -e "${red}Success Saved:${green}[$output/subdo/subs.txt]"
    exit 1
    done 2>/dev/null
}
hostlive(){
    logo
    echo -e "${red}Start ${green}[Check Host Live...]${white}"
    while [ "$site" ];do
        if [ ! -f ~/go/bin/assetfinder ];
            then
            echo -e "${red}[+]${green} Assetfinder Not Install!\n"
            exit 1
        elif [ ! -f ~/go/bin/httprobe ];
            then
            echo -e "${red}[+]${green} httprobe Not Install!\n"
            exit 1 

        else
            assetfinder --subs-only $site > $output/$site.txt
            cat $output/$site.txt | sort -u > $output/subs.txt
            rm -rf $output/$site.txt
            #cat $output/subs.txt | sort -u | httprobe -s -p http:80 | tr -d ":80" | tee -a  > $output/live/http.txt
            #cat $output/subs.txt | sort -u | httprobe -s -p https:443 | tr -d ":443" | tee -a  > $output/live/https.txt
            cat $output/subs.txt | sort -u | httprobe | tee -a  > $output/live/$site-host.txt
            rm -rf $output/$subs.txt 
        fi
    echo -e "Resluts Live:[${green}$(cat $output/live/https.txt | wc -l)${white}]"
    echo -e "${red}Success Saved:${green}[$output/live/$site-host.txt]"
    exit 1
    done 2>/dev/null
}
scraping(){
    logo
    echo -e "${red}Start ${green}[Scraping wayback for data...]${white}"
    while [ "$site" ];do
        if [ ! -f ~/go/bin/assetfinder ];
            then
            echo -e "${red}[+]${green} Assetfinder Not Install!\n"
            exit 1
        elif [ ! -f ~/go/bin/waybackurls ];
            then
            echo -e "${red}[+]${green} waybackurls Not Install!\n"
            exit 1 

        else
            assetfinder --subs-only $site > $output/$site.txt
            cat $output/$site.txt | sort -u > $output/subs.txt
            rm -rf $output/$site.txt
            cat $output/subs.txt | waybackurls | sort -u > $output/scraping/$site-list.txt
            rm -rf $output/$subs.txt 
        fi
    echo -e "Found Scraping [${green}$(cat $output/scraping/$site-list.txt | wc -l)${white}]"
    echo -e "${red}Success Saved:${green}[$output/scraping/$site-list.txt]"
    exit 1
    done 2>/dev/null
}
js(){
    logo
    echo -e "${red}Start ${green}[Scraping wayback for data js...]${white}"
    while [ "$site" ];do
        if [ ! -f ~/go/bin/assetfinder ];
            then
            echo -e "${red}[+]${green} Assetfinder Not Install!\n"
            exit 1
        elif [ ! -f ~/go/bin/waybackurls ];
            then
            echo -e "${red}[+]${green} waybackurls Not Install!\n"
            exit 1 

        else
            assetfinder --subs-only $site > $output/$site.txt
            cat $output/$site.txt | sort -u > $output/subs.txt
            rm -rf $output/$site.txt
            cat $output/subs.txt | waybackurls | sort -u > $output/scraping/$site-list.txt
            rm -rf $output/$subs.txt
            cat $output/scraping/$site-list.txt | sort -u | grep -P "\w+\.js(\?|$)" | sort -u > $output/scraping/jsurls.txt
            rm -rf $output/scraping/$site-list.txt
        fi
    echo -e "Found Scraping [${green}$(cat $output/scraping/jsurls.txt | wc -l)${white}]"
    echo -e "${red}Success Saved:${green}[$output/scraping/$site-jsurls.txt]"
    exit 1
    done 2>/dev/null
}
php(){
    logo
    echo -e "${red}Start ${green}[Scraping wayback for data php...]${white}"
    while [ "$site" ];do
        if [ ! -f ~/go/bin/assetfinder ];
            then
            echo -e "${red}[+]${green} Assetfinder Not Install!\n"
            exit 1
        elif [ ! -f ~/go/bin/waybackurls ];
            then
            echo -e "${red}[+]${green} waybackurls Not Install!\n"
            exit 1 
        else   
            assetfinder --subs-only $site > $output/$site.txt
            cat $output/$site.txt | sort -u > $output/subs.txt
            rm -rf $output/$site.txt
            cat $output/subs.txt | waybackurls | sort -u > $output/scraping/$site-list.txt
            rm -rf $output/$subs.txt
            cat $output/scraping/$site-list.txt | sort -u | grep -P "\w+\.php(\?|$)" | sort -u > $output/scraping/phpurls.txt
            rm -rf $output/scraping/$site-list.txt
        fi
    echo -e "Found Scraping [${green}$(cat $output/scraping/phpurls.txt | wc -l)${white}]"
    echo -e "${red}Success Saved:${green}[$output/scraping/$site-phpurls.txt]"
    exit 1
    done 2>/dev/null
}

asp(){
    logo
    echo -e "${red}Start ${green}[Scraping wayback for data aspx...]${white}"
    while [ "$site" ];do
        if [ ! -f ~/go/bin/assetfinder ];
            then
            echo -e "${red}[+]${green} Assetfinder Not Install!\n"
            exit 1
        elif [ ! -f ~/go/bin/waybackurls ];
            then
            echo -e "${red}[+]${green} waybackurls Not Install!\n"
            exit 1 
        else
            assetfinder --subs-only $site > $output/$site.txt
            cat $output/$site.txt | sort -u > $output/subs.txt
            rm -rf $output/$site.txt
            cat $output/subs.txt | waybackurls | sort -u > $output/scraping/$site-list.txt
            rm -rf $output/$subs.txt
            cat $output/scraping/$site-list.txt | sort -u | grep -P "\w+\.aspx(\?|$)" | sort -u > $output/scraping/aspurls.txt
            rm -rf $output/scraping/$site-list.txt
        fi
    echo -e "Found Scraping [${green}$(cat $output/scraping/aspurls.txt | wc -l)${white}]"
    echo -e "${red}Success Saved:${green}[$output/scraping/$site-aspurls.txt]"
    exit 1
    done
}
html(){
    logo
    echo -e "${red}Start ${green}[Scraping wayback for data HTML...]${white}"
    while [ "$site" ];do
        if [ ! -f ~/go/bin/assetfinder ];
            then
            echo -e "${red}[+]${green} Assetfinder Not Install!\n"
            exit 1
        elif [ ! -f ~/go/bin/waybackurls ];
            then
            echo -e "${red}[+]${green} waybackurls Not Install!\n"
            exit 1 
        else
            assetfinder --subs-only $site > $output/$site.txt
            cat $output/$site.txt | sort -u > $output/subs.txt
            rm -rf $output/$site.txt | cat $output/subs.txt | waybackurls | sort -u > $output/scraping/$site-list.txt
            rm -rf $output/$subs.txt | cat $output/scraping/$site-list.txt | sort -u | grep -P "\w+\.html(\?|$)" | sort -u > $output/scraping/htmlurls.txt
            rm -rf $output/scraping/$site-list.txt
        fi
    echo -e "Found Scraping [${green}$(cat $output/scraping/htmlurls.txt | wc -l)${white}]"
    echo -e "${red}Success Saved:${green}[$output/scraping/$site-htmlurls.txt]"
    exit 1
    done
}
dir(){
    logo
    echo -e "${red}Start ${green}[Check Status Response...]${white}"
    while [ "$site" ];do
        if [ ! -f ~/go/bin/assetfinder ];
            then
            echo -e "${red}[+]${green} Assetfinder Not Install!\n"
            exit 1
        elif [ ! -f ~/go/bin/hakrawler ];
            then
            echo -e "${red}[+]${green} hakrawler Not Install!\n"
            exit 1 
        elif [ ! -f ~/go/bin/hakcheckurl ];
            then
            echo -e "${red}[+]${green} hakcheckurl Not Install!\n"
            exit 1 
        else
            assetfinder --subs-only $site > $output/$site.txt
            cat $output/$site.txt | sort -u > $output/subs.txt 
            rm -rf $output/$site.txt | cat $output/subs.txt | hakrawler -plain | hakcheckurl | grep -v 404 > $output/dir/$site-dir.txt 
            rm -rf $output/$subs.txt  
        fi  
    echo -e "Found Status Dir [${green}$(cat $output/dir/$site-dir.txt | wc -l)${white}]"
    echo -e "${red}Success Saved:${green}[$output/dir/$site-dir.txt]"
    exit 1
    done
}

redirec(){
    logo
    echo -e "${red}Start ${green}[Check Open Redirection...]${white}"
    while [ "$site" ];do
        if [ ! -f ~/go/bin/gau ];
            then
            echo -e "${red}[+]${green} Gau Not Install!\n"
            exit 1
        
        else
            echo "$site" | assetfinder | gau --subs >  $output/redirec/$site.txt
            cat $output/redirec/$site.txt | grep -e 'redirect\|redirect=\|url\|url=\|next=\|dest=\|destination\|return\|go\|redirect_uri\|continue=\|return_path=\|externalLink=\|URL' > $output/redirec/$site-redirect.txt
        fi
    echo -e "Found Check URL Redirection [${green}$(ls $output/redirec/$site-redirec.txt | wc -l)${white}]"
    echo -e "${red}Success Saved:${green}[$output/redirec/]"
    exit 1
    done
}
ssrf(){
    logo
    echo -e "${red}Start ${green}[ Blind SSRF testing...]${white}"
    ssr=`cat callback.txt`
    while [ "$site" ];do
        if [ ! -f ~/go/bin/waybackurls ];
            then
            echo -e "${red}[+]${green} Waybackurls Not Install!\n"
            exit 1
        elif [ ! -f ~/go/bin/gau ];
            then
            echo -e "${red}[+]${green} gau Not Install!\n"
            exit 1 
        elif [ ! -f ~/go/bin/qsreplace ];
            then
            echo -e "${red}[+]${green} qsreplace Not Install!\n"
            exit 1 
        else
           waybackurls $site > $output/ssrf/$site-ssrf.txt
           gau $site >> $output/ssrf/$site-ssrf.txt
           cat $output/ssrf/$site-ssrf.txt | sort | uniq | grep "?" | qsreplace -a | qsreplace $ssr > $output/ssrf/$site-ssrf2.txt
           sed -i "s|$|\&dest=$ssr\&redirect=$ssr\&uri=$ssr\&path=$ssr\&continue=$ssr\&url=$ssr\&window=$ssr\&next=$ssr\&data=$ssr\&reference=$ssr\&ssr=$ssr\&html=$ssr\&val=$ssr\&validate=$ssr\&domain=$ssr\&callback=$ssr\&return=$ssr\&page=$ssr\&feed=$ssr\&host=$ssr&\port=$ssr\&to=$ssr\&out=$ssr\&view=$ssr\&dir=$ssr\&show=$ssr\&navigation=$ssr\&open=$ssr|g" $output/ssrf/$site-ssrf2.txt
           ffuf -w $output/ssrf/$site-ssrf2.txt -u FUZZ -t 50  > $output/ssrf/$site-ssrf3.txt
        fi
    #echo -e "Found Check SSRF [${green}$(cat $output/ssrf/$site-ssrf3.txt | wc -l)${white}]"
    echo -e "\n${red}Success Saved:${green}[$output/ssrf/$site-ssrf3.txt]"
    exit 1
    done
}
xss(){
    logo
    echo -e "${red}Start ${green}[ XSS testing...]${white}"
    xsss=`cat xss.ht`
    linee=".(jpg|jpeg|gif|css|tif|tiff|png|ttf|woff|woff2|ico|pdf|svg|txt|js)"
    while [ "$site" ];do
        if [ ! -f ~/go/bin/assetfinder ];
            then
            echo -e "${red}[+]${green} assetfinder Not Install!\n"
            exit 1
        elif [ ! -f ~/go/bin/hakrawler ];
            then
            echo -e "${red}[+]${green} hakrawler Not Install!\n"
            exit 1 
        elif [ ! -f ~/go/bin/dalfox ];
            then
            echo -e "${red}[+]${green} dalfox Not Install!\n"
            exit 1 
        elif [ ! -f ~/go/bin/qsreplace ];
            then
            echo -e "${red}[+]${green} qsreplace Not Install!\n"
            exit 1 
        else
            assetfinder  $site > $output/xss/$site.txt
            cat $output/xss/$site.txt | hakrawler -plain -usewayback -wayback | grep "=" | egrep -iv "$linee" | \
            qsreplace -a | dalfox pipe -b $xsss -o $output/xss/$site-xss.txt 
        fi
    echo -e "${red}Success Saved:${green}[$output/xss/$site-xss.txt]"
    exit 1
    done
} 
cors(){
    logo
    echo -e "${red}Start ${green}[ Cors Scanner...]${white}"
    while [ "$site" ];do
        if [ ! -f ~/go/bin/assetfinder ];
            then
            echo -e "${red}[+]${green} assetfinder Not Install!\n"
            exit 1
        elif [ ! -f ~/go/bin/subfinder ];
            then
            echo -e "${red}[+]${green} subfinder Not Install!\n"
            exit 1 
        elif [ ! -f ~/go/bin/httprobe ];
            then
            echo -e "${red}[+]${green} httprobe Not Install!\n"
            exit 1 
        elif [ ! -f ~/go/bin/CORS-Scanner ];
            then
            echo -e "${red}[+]${green} CORS-Scanner Not Install!\n"
            exit 1 
        else
            assetfinder  $site > $output/cors/$site.txt
            subfinder -silent -d $site >> $output/cors/$site.txt
            cat $output/cors/$site.txt | httprobe > $output/cors/cors.txt
            cat $output/cors/cors.txt | CORS-Scanner | tee $output/cors/$site-cors.txt
            rm -rf $output/cors/$site.txt | rm -rf $output/cors/cors.txt
        fi
    echo -e "${red}Success Saved:${green}[$output/cors/$site-cors.txt]"
    exit 1
    done
}
ssti(){
    logo
    echo -e "${red}Start ${green}[ Check SSTI Parameters...]${white}"
    while [ "$site" ];do
         if [ ! -f ~/go/bin/assetfinder ];
            then
            echo -e "${red}[+]${green} assetfinder Not Install!\n"
            exit 1
        elif [ ! -f ~/go/bin/subfinder ];
            then
            echo -e "${red}[+]${green} subfinder Not Install!\n"
            exit 1 
        elif [ ! -f ~/go/bin/waybackurls ];
            then
            echo -e "${red}[+]${green} waybackurls Not Install!\n"
            exit 1 
        elif [ ! -f ~/go/bin/gf ];
            then
            echo -e "${red}[+]${green} gf Not Install!\n"
            exit 1 
        else
            assetfinder  $site > $output/ssti/$site.txt
            subfinder -silent -d $site >> $output/ssti/$site.txt
            cat $output/ssti/$site.txt | waybackurls | sort -u > $output/ssti/ssti.txt
            cat $output/ssti/ssti.txt | gf ssti | tee -a > $output/ssti/$site-ssti.txt
            rm -rf $output/ssti/$site.txt | rm -rf $output/ssti/ssti.txt
        fi
    echo -e "Found Check SSTI Parameters [${green}$(cat $output/ssti/$site-ssti.txt | wc -l)${white}]"
    echo -e "${red}Success Saved:${green}[$output/ssti/$site-ssti.txt]"
    exit 1
    done
}
check_r(){
    logo
    echo -e "${red}Start ${green}[ Check redirec Parameters...]${white}"
    while [ "$site" ];do
        if [ ! -f ~/go/bin/assetfinder ];
            then
            echo -e "${red}[+]${green} assetfinder Not Install!\n"
            exit 1
        elif [ ! -f ~/go/bin/subfinder ];
            then
            echo -e "${red}[+]${green} subfinder Not Install!\n"
            exit 1 
        elif [ ! -f ~/go/bin/waybackurls ];
            then
            echo -e "${red}[+]${green} waybackurls Not Install!\n"
            exit 1 
        elif [ ! -f ~/go/bin/gf ];
            then
            echo -e "${red}[+]${green} gf Not Install!\n"
            exit 1 
        else
            assetfinder  $site > $output/redirec/$site.txt
            subfinder -silent -d $site >> $output/redirec/$site.txt
            cat $output/redirec/$site.txt | waybackurls | sort -u > $output/redirec/redirec.txt
            cat $output/redirec/redirec.txt | gf redirect | tee -a > $output/redirec/$site-redirec.txt
            rm -rf $output/redirec/$site.txt | rm -rf $output/redirec/redirec.txt
        fi
    echo -e "Found Check redirec Parameters [${green}$(cat $output/redirec/$site-redirec.txt | wc -l)${white}]"
    echo -e "${red}Success Saved:${green}[$output/redirec/$site-redirec.txt]"
    exit 1
    done
}
idor(){
    logo
    echo -e "${red}Start ${green}[ Check IDOR Parameters...]${white}"
    while [ "$site" ];do
        if [ ! -f ~/go/bin/assetfinder ];
            then
            echo -e "${red}[+]${green} assetfinder Not Install!\n"
            exit 1
        elif [ ! -f ~/go/bin/subfinder ];
            then
            echo -e "${red}[+]${green} subfinder Not Install!\n"
            exit 1 
        elif [ ! -f ~/go/bin/waybackurls ];
            then
            echo -e "${red}[+]${green} waybackurls Not Install!\n"
            exit 1 
        elif [ ! -f ~/go/bin/gf ];
            then
            echo -e "${red}[+]${green} gf Not Install!\n"
            exit 1 
        else
            assetfinder  $site > $output/idor/$site.txt
            subfinder -silent -d $site >> $output/idor/$site.txt
            cat $output/idor/$site.txt | waybackurls | sort -u > $output/idor/idor.txt
            cat $output/idor/idor.txt | gf idor | tee -a > $output/idor/$site-idor.txt
            rm -rf $output/idor/$site.txt | rm -rf $output/idor/idor.txt
        fi
    echo -e "Found Check IDOR Parameters [${green}$(cat $output/idor/$site-idor.txt | wc -l)${white}]"
    echo -e "${red}Success Saved:${green}[$output/idor/$site-idor.txt]"
    exit 1
    done
}
rce(){
    logo
    echo -e "${red}Start ${green}[ Check RCE Parameters...]${white}"
    while [ "$site" ];do
        if [ ! -f ~/go/bin/assetfinder ];
            then
            echo -e "${red}[+]${green} assetfinder Not Install!\n"
            exit 1
        elif [ ! -f ~/go/bin/subfinder ];
            then
            echo -e "${red}[+]${green} subfinder Not Install!\n"
            exit 1 
        elif [ ! -f ~/go/bin/waybackurls ];
            then
            echo -e "${red}[+]${green} waybackurls Not Install!\n"
            exit 1 
        elif [ ! -f ~/go/bin/gf ];
            then
            echo -e "${red}[+]${green} gf Not Install!\n"
            exit 1 
        else
            assetfinder  $site > $output/rce/$site.txt
            subfinder -silent -d $site >> $output/rce/$site.txt
            cat $output/rce/$site.txt | waybackurls | sort -u > $output/rce/rce.txt
            cat $output/rce/rce.txt | gf rce | tee -a > $output/idor/$site-rce.txt
            rm -rf $output/rce/$site.txt | rm -rf $output/rce/rce.txt
        fi
    echo -e "Found Check RCE Parameters [${green}$(cat $output/rce/$site-rce.txt | wc -l)${white}]"
    echo -e "${red}Success Saved:${green}[$output/rce/$site-rce.txt]"
    exit 1
    done
}
lfi(){
    logo
    echo -e "${red}Start ${green}[ Check LFI Parameters...]${white}"
    while [ "$site" ];do
        if [ ! -f ~/go/bin/assetfinder ];
            then
            echo -e "${red}[+]${green} assetfinder Not Install!\n"
            exit 1
        elif [ ! -f ~/go/bin/subfinder ];
            then
            echo -e "${red}[+]${green} subfinder Not Install!\n"
            exit 1 
        elif [ ! -f ~/go/bin/waybackurls ];
            then
            echo -e "${red}[+]${green} waybackurls Not Install!\n"
            exit 1 
        elif [ ! -f ~/go/bin/gf ];
            then
            echo -e "${red}[+]${green} gf Not Install!\n"
            exit 1 
        else
            assetfinder  $site > $output/lfi/$site.txt
            subfinder -silent -d $site >> $output/lfi/$site.txt
            cat $output/lfi/$site.txt | waybackurls | sort -u > $output/lfi/lfi.txt
            cat $output/lfi/lfi.txt | gf lfi | tee -a > $output/lfi/$site-lfi.txt
            rm -rf $output/lfi/$site.txt | rm -rf $output/lfi/lfi.txt
        fi
    echo -e "Found Check LFI Parameters [${green}$(cat $output/lfi/$site-lfi.txt | wc -l)${white}]"
    echo -e "${red}Success Saved:${green}[$output/lfi/$site-lfi.txt]"
    exit 1
    done
}
sqli(){
    logo
    echo -e "${red}Start ${green}[ Check SQLI Parameters...]${white}"
    while [ "$site" ];do
        if [ ! -f ~/go/bin/assetfinder ];
            then
            echo -e "${red}[+]${green} assetfinder Not Install!\n"
            exit 1
        elif [ ! -f ~/go/bin/subfinder ];
            then
            echo -e "${red}[+]${green} subfinder Not Install!\n"
            exit 1 
        elif [ ! -f ~/go/bin/waybackurls ];
            then
            echo -e "${red}[+]${green} waybackurls Not Install!\n"
            exit 1 
        elif [ ! -f ~/go/bin/gf ];
            then
            echo -e "${red}[+]${green} gf Not Install!\n"
            exit 1 
        else
            assetfinder  $site > $output/sqli/$site.txt
            subfinder -silent -d $site >> $output/sqli/$site.txt
            cat $output/sqli/$site.txt | waybackurls | sort -u > $output/sqli/sqli.txt
            cat $output/sqli/sqli.txt | gf sqli | tee -a > $output/lfi/$site-sqli.txt
            rm -rf $output/sqli/$site.txt | rm -rf $output/sqli/sqli.txt
        fi
    echo -e "Found Check SQLI Parameters [${green}$(cat $output/sqli/$site-sqli.txt | wc -l)${white}]"
    echo -e "${red}Success Saved:${green}[$output/sqli/$site-sqli.txt]"
    exit 1
    done
}
take(){
    logo
    echo -e "${red}Start ${green}[ Check Takeover...]${white}"
    while [ "$site" ];do
        if [ ! -f ~/go/bin/assetfinder ];
            then
            echo -e "${red}[+]${green} assetfinder Not Install!\n"
            exit 1
        elif [ ! -f ~/go/bin/subfinder ];
            then
            echo -e "${red}[+]${green} subfinder Not Install!\n"
            exit 1 
        elif [ ! -f ~/go/bin/waybackurls ];
            then
            echo -e "${red}[+]${green} waybackurls Not Install!\n"
            exit 1 
        elif [ ! -f ~/go/bin/gf ];
            then
            echo -e "${red}[+]${green} gf Not Install!\n"
            exit 1 
        else
            assetfinder $site > $output/takeover/$site.txt
            subfinder -silent -d $site >> $output/takeover/$site.txt
            cat $output/takeover/$site.txt | waybackurls | sort -u > $output/takeover/takeover.txt
            cat $output/takeover/takeover.txt | gf takeovers | tee -a > $output/takeover/$site-takeover.txt
            rm -rf $output/takeover/$site.txt | rm -rf $output/takeover/takeover.txt
        fi
    echo -e "Found Check Takeover  [${green}$(cat $output/takeover/$site-takeover.txt | wc -l)${white}]"
    echo -e "${red}Success Saved:${green}[$output/takeover/$site-takeover.txt]"
    exit 1
    done
}
ssrf2(){
    logo
    echo -e "${red}Start ${green}[ Check ssrf...]${white}"
    while [ "$site" ];do
        if [ ! -f ~/go/bin/assetfinder ];
            then
            echo -e "${red}[+]${green} assetfinder Not Install!\n"
            exit 1
        elif [ ! -f ~/go/bin/waybackurls ];
            then
            echo -e "${red}[+]${green} waybackurls Not Install!\n"
            exit 1 
        elif [ ! -f ~/go/bin/gf ];
            then
            echo -e "${red}[+]${green} gf Not Install!\n"
            exit 1 
        else
            echo -en "$site" | assetfinder | waybackurls | sort -u > $output/ssrf/ssrf.txt
            cat $output/ssrf/ssrf.txt | gf ssrf | tee -a > $output/ssrf/$site-ssrf.txt
            rm -rf $output/ssrf/$site.txt | rm -rf $output/ssrf/ssrf.txt
        fi
    echo -e "Found Check ssrf  [${green}$(cat $output/ssrf/$site-ssrf.txt | wc -l)${white}]"
    echo -e "${red}Success Saved:${green}[$output/ssrf/$site-ssrf.txt]"
    exit 1
    done
}
verbose(){
    logo
    echo -e "${red}Start ${green}[ Verbose...]${white}"
    while [ "$site" ];do
        if [ ! -f ~/go/bin/assetfinder ];
            then
            echo -e "${red}[+]${green} assetfinder Not Install!\n"
            exit 1
        elif [ ! -f ~/go/bin/waybackurls ];
            then
            echo -e "${red}[+]${green} waybackurls Not Install!\n"
            exit 1 
        elif [ ! -f ~/go/bin/httpx ];
            then
            echo -e "${red}[+]${green} Httpx Not Install!\n"
            exit 1
        elif [ ! -f /usr/bin/jq ];
            then
            echo -e "${red}[+]${green} jq Not Install!\n"
            exit 1 
        else
            echo -en "$site" | assetfinder | waybackurls | sort -u > $output/verbose/out.txt
            cat $output/verbose/out.txt | httpx -silent -content-length -status-code -verbose -title -vhost -json | jq > $output/verbose/$site-out.json
            rm -rf $output/verbose/out.txt 
        fi
    echo -e "Found Check verbose  [${green}$(cat $output/ssrf/$site-ssrf.txt | wc -l)${white}]"
    echo -e "${red}Success Saved:${green}[$output/ssrf/$site-ssrf.txt]"
    exit 1
    done
}
logo(){
 echo -e "${red}

oo_____oo_ooooooo______oooo_________________________________
_oo___oo__oo____oo___oo____oo_oo_ooo___ooooo___oooo___oooo__
__oo_oo___oo____oo__oo________ooo___o_oo___oo_oo___o_oo___o_
___ooo____ooooooo___oo________oo______oo___oo___oo_____oo___
__oo_oo___oo____oo___oo____oo_oo______oo___oo_o___oo_o___oo_
_oo___oo__oo_____oo____oooo___oo_______ooooo___oooo___oooo__
____________________________________________________________ ${blue}
                            Codename:${green}$codename ${red}
                            Version:${green}$ver ${white}
            github:$follow
"
}
help(){
        logo
        echo -e ${green}
        echo "Example: $0 -u/--url example.site"
        echo "         $0 <arguments> example.site <arguments> "
        echo
        echo "Optional Arguments:"
        echo   "       -h  --help     show this help message and exit"
        echo   "       -s  --subdo    Check Subdomains "
        echo   "       -H  --host     Host Live Check"
        echo   "       -sw --scrw     Scraping wayback for data"
        echo   "                -js  Jsurls "
        echo   "                -php Phpurls"
        echo   "                -asp ASP"
        echo   "                -html Html"
        echo   "       -D  --dir      Check Dir Status Response"
        echo   "       -r  normal     Check open redirection"
        echo   "                -redirec  Check redirec Parameters"
        echo   "       -Ss --ssrf     Blind SSRF testing"
        echo   "       -xs --xss      Check Parameter XSS"
        echo   "       -cs --cors     CORS misconfiguration scanner"
        echo   "       -gf            GF parameters grep"
        echo   "                -ssti Check SSTI Parameters"
        echo   "                -idor Check IDOR Parameters"
        echo   "                -rce  Check RCE Parameters"
        echo   "                -lfi  Check LFI Parameters"
        echo   "                -sqli Check SQLI Parameters"
        echo   "                -ssrf Check SQLI Parameters"   
        echo   "       -T --takeover  Grep takeover"
        echo   "       -v --verbose   Verbose status code"
        echo   "       -o             Outfile"
        exit 1
}
if [ -z "$site" ];then
    logo
else
while [ "$site" ]; do
    case "$site" in
        "-v" | "--verbose") site="$2"
            if [[ $3 == "-o" ]];
                then
                output="$4/$site"
                mkdir -p "$output"/"verbose"
                verbose $site
            else
                output="$site"
                mkdir -p "$output"/"verbose"
                verbose $site
            fi
            ;;
        "-T" | "--takeover") site="$2"
            if [[ $3 == "-o" ]];
                then
                output="$4/$site"
                mkdir -p "$output"/"takeover"
                take $site
            else
                output="$site"
                mkdir -p "$output"/"takeover"
                take $site
            fi
            ;;
        "-gf") site="$2"
            if [[ $3 == "-ssti" ]];
                then
                output="$site"
                mkdir -p "$output"/"ssti"
                ssti $site
            elif [[ $3 == "-idor" ]];
                then
                output="$site"
                mkdir -p "$output"/"idor"
                idor $site
            elif [[ $3 == "-rce" ]];
                then
                output="$site"
                mkdir -p "$output"/"rce"
                rce $site
            elif [[ $3 == "-lfi" ]];
                then
                output="$site"
                mkdir -p "$output"/"lfi"
                lfi $site
            elif [[ $3 == "-sqli" ]];
                then
                output="$site"
                mkdir -p "$output"/"sqli"
                sqli $site
            elif [[ $3 == "-ssrf" ]];
                then
                output="$site"
                mkdir -p "$output"/"ssrf"
                ssrf2 $site
            else
                logo
                exit 1
            fi
            ;;

        "-cs" | "--cors") site="$2"
            if [[ $3 == "-o" ]];
                then
                output="$4/$site"
                mkdir -p "$output"/"cors"
                cors $site

            else
                output="$site"
                mkdir -p "$output"/"cors"
                cors $site

            fi
            ;;
        "-xs" | "--xss") site="$2"
            if [[ $3 == "-o" ]];
                then
                output="$4/$site"
                mkdir -p "$output"/"xss"
                xss $site

            else
                output="$site"
                mkdir -p "$output"/"xss"
                xss $site

            fi
            ;;
        "-u" | "--url") site="$2"
            if [[ $3 == "-o" ]];
                then
                output="$4/$site"
                mkdir -p "$output"
                all $site
            else
                output="$site"
                mkdir -p "$output"
                all $site
            fi
            ;;

        "-Ss" | "--ssrf") site="$2"
            if [[ $3 == "-o" ]];
                then
                output="$4/$site"
                mkdir -p "$output"/"ssrf"
                ssrf $site
            else
                output="$site"
                mkdir -p "$output"/"ssrf"
                ssrf $site
            fi
            ;;
        "-r" ) site="$2"
            if [[ $3 == "-o" ]]; 
                then
                output="$4/$site"
                mkdir -p "$output"/"redirec"
                redirec $site
            elif [[ $3 == "-redirec" ]]; 
                then
                output="$site"
                mkdir -p "$output"/"redirec"
                check_r $site

            else
                output="$site"
                mkdir -p "$output"/"redirec"
                redirec $site
            fi
            ;;
        "-s" | "--subdo") site="$2"
            if [[ "$3" == '-o' ]];
            then
                output="$4/$site"
                mkdir -p "$output"/"subdo"
                subdo $site
            else
                output="$site"
                mkdir -p "$output"/"subdo"
                subdo $site
                continue
            fi
            
            ;;
        "-h" | "--help")
            help
            exit 1
            ;;
        "-D" | "--dir") 
            site="$2"
                    if [[ $3 == "-o" ]]
                    then
                        output="$4/$site"
                        mkdir -p "$output"/"dir"
                        dir $site
                    else
                        output="$site"
                        mkdir -p "$output"/"dir"
                        dir $site
                        continue
                    fi
            ;;
        "-H" | "--host") 
            site="$2"
                    if [[ $3 == "-o" ]]
                    then
                        output="$4/$site"
                        mkdir -p "$output"/"live"
                        hostlive $site
                    else
                        output="$site"
                        mkdir -p "$output"/"live"
                        hostlive $site
                        continue
                    fi
            ;;
        "-sw" | "--scrw") 
            site="$2"
                    if [[ $3 == "-o" ]]
                    then
                        output="$4/$site"
                        mkdir -p "$output"/"scraping"
                        scraping $site
                    elif [[ $3 == "-js" ]]
                    then
                        output="$site"
                        mkdir -p "$output/scraping"
                        js $site
                        continue
                    elif [[ $3 == "-php" ]]
                    then
                        output="$site"
                        mkdir -p "$output"/"scraping"
                        php $site
                        continue
                    elif [[ $3 == "-asp" ]]
                    then
                        output="$site"
                        mkdir -p "$output"/"scraping"
                        asp $site
                        continue
                    elif [[ $3 == "-html" ]]
                    then
                        output="$site"
                        mkdir -p "$output"/"scraping"
                        html $site
                        continue
                    else
                        output="$4/$site"
                        mkdir -p "$output"/"scraping"
                        scraping $site
                    fi
            shift 
            break
            ;;
        esac
        shift
done
fi